# Generated by Django 5.2.4 on 2025-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('template', 'Templates'), ('plugin', 'Plugins'), ('file', 'Files'), ('image', 'Images'), ('document', 'Documents'), ('code', 'Code Snippets'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='resources/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/')),
                ('download_url', models.URLField(blank=True, help_text='External download link if file is hosted elsewhere', null=True)),
                ('file_size', models.CharField(blank=True, help_text='e.g., 2.5 MB', max_length=20)),
                ('file_type', models.CharField(blank=True, help_text='e.g., ZIP, PDF, PNG', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
